### ISSUE TITLE
Welcome back!

### ISSUE THREAD

**Issue by shinycolororange** [BeansGalaxy/Beans-Backpacks-3#1]
It's great to see that my favorite backpack mod developer is creating a mod for version 1.21.1 with even better features! I absolutely love the ideas so far, and I'm especially thrilled that you can now see tools on your back!

I know it's still in the super early alpha stage, and I hope it's not too early to provide feedback. If I may, I’d like to suggest a better placement for the tool icon—perhaps mirroring the offhand position but on the opposite side.

Anyway, I can't wait to see more updates and wish you a fantastic day!
![2024-11-25_12 13 06](https://github.com/user-attachments/assets/a5ce2dce-45fc-4155-8ec0-b7db6f255940)

**Comment by BeansGalaxy** [comment]
![2024-11-26_05 06 41](https://github.com/user-attachments/assets/d7ad3a7f-f6e7-42e4-8c63-a5620782c7b9)

:) Congrats on being the first issue!

If your player was left handed then the offhand shows up on the right and vice versa so I was too lazy to work out what coordinates the slots had to be while I was testing it. Made it a config option too just incase you wanted to move it back. Keep an eye out for 0.5-alpha!
