### ISSUE TITLE
Unexpected GUI Rendering

### ISSUE THREAD

**Issue by Lufurrius** [BeansGalaxy/Beans-Backpacks-3#10]
Since version f-0.3-beta, setting `tool_belt_size` and `shorthand_size` to 0 will not result in the associated GUI not being rendered.
This has been an issue with the HUD with all versions that I've tested with, and since the specified version the inventory slots will not be visible until interacted with, after which they will not be visible again until after restarting the game. *Sometimes* they aren't when loading up a creative world they'll be hidden off the bat.

Producing the Issue:
Version f-0.3-beta, Fabric
Set `tool_belt_size` and `shorthand_size` to 0 inside `beansbackpacks-common.json5`. Load into a survival world.

What is Expected:
The associated slots to be disabled and not visible to players.

What Happens:
Despite being unusable, the associated HUD element is always visible, and the inventory slots will still be visible until an attempted interaction when they'll vanish until restarting the game.

____
That aside, - the tech presented here is really impressive, and the backpack system presented here is is quite fun and appropriate for more vanillaesque gameplay. Understand that the project is still quite early on, and appreciate the work being put in to refine it - can't wait to see it grow and define more into your vision over time.

**Comment by BeansGalaxy** [comment]
Thanks for pointing this out!

Super simple fix, the HUD wasn't checking if the size was zero and the slots were checking the wrong value and not properly shrinking the slots on load. Interacting with the slots would check the correct value and actually shrink them.

Keep an eye out for **0.4-beta**

**Comment by BeansGalaxy** [comment]
New version [0.4-beta](https://modrinth.com/mod/beans-backpacks-3/changelog) is live!
