### ISSUE TITLE
Cofig on the server does not work

### ISSUE THREAD

**Issue by macuguita** [BeansGalaxy/Beans-Backpacks-3#12]
Whenever i run beans backpack on a server the config does not show up in either the config folder or the world/serverconfig folder, whenever you add the config manually into the server it just completely ignores it

**Comment by BeansGalaxy** [comment]
Config hasn't been really tested on servers, I'll check this out and see what I find

**Comment by BeansGalaxy** [comment]
New version [0.4-beta](https://modrinth.com/mod/beans-backpacks-3/changelog) is live!
