### ISSUE TITLE
small crash

### ISSUE THREAD

**Issue by shinycolororange** [BeansGalaxy/Beans-Backpacks-3#2]
Hi there,

I wanted to share a small crash report I encountered. It happens when swapping an axe from the weapon slot:
[Crash Report Link](https://mclo.gs/afWX0Zw)

Also, before anyone reports this as a false crash, I recommend updating the mod's description for version 1.21 to explicitly mention compatibility with 1.21.1. Otherwise, it might crash on startup with 1.21.1. (I manually edited it myself while testing the mod.)

By the way, will the keep inventory option for the backpack be added in a future update? I've always loved this feature and would be lovely to see it return!

Love your work, and have a great day!

**Comment by BeansGalaxy** [comment]
Solved! The Shorthand redirects a lot of the visual code when its equipped but not much of the logical code. Better Combat redirects a lot of the logical code for what the player has in their hand and that was causing the game to crash. Pretty fun mod too, this would've gone quicker if I wasn't summoning a bunch of pillagers to slaughter while testing.

Keep an eye out for **0.1-beta**. I'll also add a config option to keep Back, Tool Bar, and Shorthand items on death.

**Comment by BeansGalaxy** [comment]
Beta 0-1 is live on modrinth!
