### ISSUE TITLE
(1.21.1) [Beta 0.2 Fabric] Crash when using number keys to input items into backpack

### ISSUE THREAD

**Issue by OozyLucy** [BeansGalaxy/Beans-Backpacks-3#5]
Using the number keys to input an item into a backpack on the ground crashes the game.

https://mclo.gs/1wAg1CE

**Comment by BeansGalaxy** [comment]
I salute you. Thanks for all the resources to make each bug easy to track down. All of them are fixed in Beta 0.3 and live on Modrinth now :))))
