### ISSUE TITLE
(1.21.1) [Beta 0.2 Fabric] Unable to click items into backpack in creative mode (like when using a bundle)

### ISSUE THREAD

**Issue by OozyLucy** [BeansGalaxy/Beans-Backpacks-3#6]
After the first item, it becomes impossible to put any items in or take any out.

![2024-12-0809-54-10](https://github.com/user-attachments/assets/f99ca3be-806c-4435-805c-216a717730f0)

**Comment by BeansGalaxy** [comment]
Fixed in **0.3-beta**
