### ISSUE TITLE
(1.21.1) [Beta 0.2 Fabric] HUD elements are drawn underneath overlays (like the vignette or portal overlay)

### ISSUE THREAD

**Issue by OozyLucy** [BeansGalaxy/Beans-Backpacks-3#7]
vignette:

![image](https://github.com/user-attachments/assets/24cc9776-91ce-4a52-ac3a-e1b5e6deb8f6)

portal:

![image](https://github.com/user-attachments/assets/56c3da7a-1698-4719-9ef3-a29acc03a362)

**Comment by BeansGalaxy** [comment]
Fixed in **0.3-beta**
